### ISSUE TITLE
Replacing text with icon for send message button

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/Mumble#1]
add a simple icon same as WhatsApp for the send message button

**Comment by Godzilla5111** [comment]
Hey @shrinish123, please assign it to me!

**Comment by reapedjuggler** [comment]
Hey all, i would like to work on this issue if it's still available to solve

**Comment by shrinish123** [comment]
@Godzilla5111  I hae assigned you this issue

**Comment by shrinish123** [comment]
@reapedjuggler sorry I have already assigned it to @Godzilla5111, if  he  takes back then I will assign it to you :) 
I have other respo in KWOC , GuessMovie, there is a lot of HTML CSS issues which you can work on

**Comment by Godzilla5111** [comment]
Hey @shrinish123 , please check the pull request.

**Comment by shrinish123** [comment]
Ya i merged your pull request

**Comment by Godzilla5111** [comment]
Thanks @shrinish123 !
