### ISSUE TITLE
Implement voice messages

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/Mumble#6]
We can also implement  sending voice messages same as sharing pictures

**Comment by reapedjuggler** [comment]
Hey folks! i would like to work on this issue.

**Comment by shrinish123** [comment]
@reapedjuggler  ya sure you can start working on this I am assigning this to you

**Comment by reapedjuggler** [comment]
Some resources and direction approach on how to implement it? I found something called webRTC but wasn't able to implement it :)

**Comment by shrinish123** [comment]
Even I'm not experienced in doing this earlier.
But I think this link will surely help you 
<a href="https://medium.com/@onwuka_gideon/how-to-integrate-voice-messages-into-your-stream-chat-application-2ccabd9ff1ad">How to implement voice messages in NodeJS</a>

**Comment by shrinish123** [comment]
If you have any difficulty feel free to message me over here or slack, but prefer you to join slack for better communication

**Comment by shrinish123** [comment]
@reapedjuggler  note that you have to commit something before 14th , so even if you are not able to completely provide me the feature you can commit whatever you have  before 14th for the mid evals

**Comment by Dineshhardasani** [comment]
@shrinish123  i would like to work on this issue.

**Comment by shrinish123** [comment]
oh okay, I actually didn't check, you can work on this issue. All the Best

**Comment by shrinish123** [comment]
Thanks a lot, @Dineshhardasani, I tested your code, and absolutely works great. Once again Thanks a lot for your contribution. All the best for your future endeavors. You can still contribute even after the end of KWOC.
